MANAGER_SOURCES = \
        manager/defines.h \
        manager/manager.c \
        manager/manager.h \
        manager/managerReq.h \
        manager/pagetable.c \
        manager/pagetable.h \
        manager/SPSC_queue.h